### ISSUE TITLE
Possibility of including Go to Source Definition?

### ISSUE THREAD

**Issue by ajitid** [jose-elias-alvarez/typescript.nvim#13]
Ref: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/?q=1#go-to-source-definition

Unsure if this plugin can expose above functionality, or if it is just unavailable to us because we're relying on an LSP server and VS Code isn't.

**Comment by jose-elias-alvarez** [comment]
This would have to be implemented in `typescript-language-server` since it involves sending a request to `tsserver` (which we don't have direct access to in Neovim). 

It's a bit of an unusual situation, since to my knowledge there's nothing matching this in the LSP specification, so it would be up to the `typescript-language-server` folks to determine if / how they want to handle this feature and expose it. Definitely worth opening an issue there if this is something you're interested in.

**Comment by ajitid** [comment]
Hey @jose-elias-alvarez, this has been added in typescript-language-server ([readme](https://github.com/typescript-language-server/typescript-language-server/blob/4c0fa34be1aa1b6dd2ee385e6a142f03b40f817e/README.md?plain=1#L283), [pull request](https://github.com/typescript-language-server/typescript-language-server/pull/560)).

**Comment by jose-elias-alvarez** [comment]
Excellent, thanks for the update! I am traveling but will investigate this when I get back. From looking at the PR, I don't think it should be too difficult to add support here.
