### ISSUE TITLE
:TypeScriptRenameFile alters buffers but not referencing files

### ISSUE THREAD

**Issue by thraizz** [jose-elias-alvarez/typescript.nvim#15]
Hi, I noticed that when renaming files, the file gets renamed but the references and imports are not saved. These references are only changed in the buffer, I have to go to each open buffer and save it. Is this intended behavior or a bug? :smiley_cat: Thanks!

For reference, im running NVIM v0.8.0-dev+452-gb2ed439bd5 with the typescript.nvim at commit 2b139a2032de0e3dafaae914f4def62234214469

**Comment by jose-elias-alvarez** [comment]
Yep, this is normal behavior. I usually just run `:wa` after renaming. I guess it's possible to make this optional, and it might even make sense as a default if that's how VS Code handles it.

**Comment by thraizz** [comment]
Might be cool to have this somehow configured, for now i just adapted the :wa as well :D

**Comment by jose-elias-alvarez** [comment]
For future reference if anyone wants to work on this: I checked how VS Code handles this, and it also loads all changed files and leaves them dirty without automatically saving. The difference is that it's more obvious that this is happening in VS Code because the user can immediately see all the open tabs.

It'd be easy enough to add an option to the Lua API, e.g.:

```lua
require("typescript").renameFile(source, target, { save = true })
```

But it's unclear how this would translate to the Vim command, since `:TypescriptRenameFile!` (with a bang) is already used to force overwriting the target. Since this command is always asynchronous, it might be worth firing a custom autocommand event and letting users hook into that.

**Comment by intagaming** [comment]
I was not aware of the fact that there are unsaved buffers in the background waiting to just interrupt me from quitting Neovim. I lost an hour or two just to stumble across this GitHub issue. So I figured, a notification about `:wa` doesn't hurt. Currently using this to rename/move files in a TypeScript project. Maybe it will help, maybe not. Been using it for about 2 weeks in 2 renaming sessions, never missed a `:wa` since: 

```lua
vim.keymap.set('n', '<leader>trf', function()
    local current_buf = vim.api.nvim_buf_get_name(0)

    vim.ui.input({
        prompt = "New path: ",
        default = current_buf,
    }, function(text)
        if text == "" then return end

        local ok = require("typescript").renameFile(current_buf, text)
        if not ok then return end

        print("Renamed. Remember to :wa to save buffers after renaming!")
    end)
```

**Comment by jose-elias-alvarez** [comment]
To my knowledge there are no other language servers that provide this kind of notification functionality, so while the above seems fine as a local modification, I don't know about including it here (especially since we'd need an inevitable option to disable it).
