### ISSUE TITLE
Add support for refactorings (`_typescript.applyRefactoring`)

### ISSUE THREAD

**Issue by kristijanhusak** [jose-elias-alvarez/typescript.nvim#32]
Hi,

I noticed that typescript-language-server has "refactorings": https://github.com/typescript-language-server/typescript-language-server#apply-refactoring , but I'm not sure if these refactorings are actually code actions (extract to method, etc), or it's something else?

**Comment by jose-elias-alvarez** [comment]
Looking at [the documentation](https://code.visualstudio.com/docs/typescript/typescript-refactoring#_refactoring), I think these correspond to code actions (some of which are only accessible by using `vim.lsp.buf.range_code_action()`. We did need to add support for rename handling in #17, but otherwise I think these should already work. Let me know if that's not the case.

**Comment by kristijanhusak** [comment]
Yeah those are already accessible through code actions, so I guess we are ok. Thanks for investigating.
