### ISSUE TITLE
Can't tell what this plugin offers

### ISSUE THREAD

**Issue by dbalatero** [jose-elias-alvarez/typescript.nvim#43]
Hi! I landed here from https://github.com/rockerBOO/awesome-neovim.

However, when I got to the README, I couldn't tell what this plugin offers vs. `lspconfig.tsserver.setup()`

* Is it speed?
* More features of some kind?
* Are there things I should be excited about that this plugin provides?

Possible to update the README with more context?

**Comment by jose-elias-alvarez** [comment]
The README says:

> A minimal `typescript-language-server` integration plugin to set up the language
server via [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) and add
commands for convenience. 

The Features section then lists exactly what those commands are. I'm not sure what I can do to make things clearer, but I'm open to a PR if you feel that it's confusing.

**Comment by jose-elias-alvarez** [comment]
Well, they are built into `tsserver` (and accessible via `typescript-language-server`). Since these are off-spec features, this is essentially a glue plugin that makes it easier to access a broader set of `tsserver` functionality from Neovim. It's theoretically possible for a user to, say, copy-paste the code for a single action into their config and use it that way (though the fact that we generate Lua code from TypeScript complicates things).

The whole `tsserver` situation is messy, so if the takeaway from the README is "install this plugin to get these features" I am happy with that, but again, if you think we could clarify things, feel free to open a PR.

**Comment by jose-elias-alvarez** [comment]
Closing this, but feel free to open a PR to improve documentation if you feel that there's a gap.
